<?php
$data = array (
  0 => 
  array (
    'cat_id' => '20',
    'cat_name' => '戒指',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '93',
  ),
  1 => 
  array (
    'cat_id' => '31',
    'cat_name' => '项链',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  2 => 
  array (
    'cat_id' => '21',
    'cat_name' => '耳钉',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  3 => 
  array (
    'cat_id' => '19',
    'cat_name' => '手链',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  4 => 
  array (
    'cat_id' => '26',
    'cat_name' => '胸针',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  5 => 
  array (
    'cat_id' => '28',
    'cat_name' => '耳钩',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
  ),
  6 => 
  array (
    'cat_id' => '23',
    'cat_name' => '耳针',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  7 => 
  array (
    'cat_id' => '22',
    'cat_name' => '吊坠',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '42',
  ),
  8 => 
  array (
    'cat_id' => '27',
    'cat_name' => '袖扣',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  9 => 
  array (
    'cat_id' => '25',
    'cat_name' => '手镯',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  10 => 
  array (
    'cat_id' => '24',
    'cat_name' => '耳坠',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  11 => 
  array (
    'cat_id' => '30',
    'cat_name' => '价格：3000~5000',
    'measure_unit' => '',
    'parent_id' => '28',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  12 => 
  array (
    'cat_id' => '29',
    'cat_name' => '珍珠尺寸：7mm~10mm',
    'measure_unit' => '',
    'parent_id' => '28',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
);
?>