<?php
$data = array (
  20 => 
  array (
    'cat_id' => '20',
    'cat_name' => '戒指',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '93',
    'level' => 0,
    'id' => '20',
    'name' => '戒指',
  ),
  31 => 
  array (
    'cat_id' => '31',
    'cat_name' => '项链',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '31',
    'name' => '项链',
  ),
  21 => 
  array (
    'cat_id' => '21',
    'cat_name' => '耳钉',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '21',
    'name' => '耳钉',
  ),
  19 => 
  array (
    'cat_id' => '19',
    'cat_name' => '手链',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '19',
    'name' => '手链',
  ),
  26 => 
  array (
    'cat_id' => '26',
    'cat_name' => '胸针',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '26',
    'name' => '胸针',
  ),
  28 => 
  array (
    'cat_id' => '28',
    'cat_name' => '耳钩',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 0,
    'id' => '28',
    'name' => '耳钩',
  ),
  30 => 
  array (
    'cat_id' => '30',
    'cat_name' => '价格：3000~5000',
    'measure_unit' => '',
    'parent_id' => '28',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '30',
    'name' => '价格：3000~5000',
  ),
  29 => 
  array (
    'cat_id' => '29',
    'cat_name' => '珍珠尺寸：7mm~10mm',
    'measure_unit' => '',
    'parent_id' => '28',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '29',
    'name' => '珍珠尺寸：7mm~10mm',
  ),
  23 => 
  array (
    'cat_id' => '23',
    'cat_name' => '耳针',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '23',
    'name' => '耳针',
  ),
  22 => 
  array (
    'cat_id' => '22',
    'cat_name' => '吊坠',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '42',
    'level' => 0,
    'id' => '22',
    'name' => '吊坠',
  ),
  27 => 
  array (
    'cat_id' => '27',
    'cat_name' => '袖扣',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '27',
    'name' => '袖扣',
  ),
  25 => 
  array (
    'cat_id' => '25',
    'cat_name' => '手镯',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '25',
    'name' => '手镯',
  ),
  24 => 
  array (
    'cat_id' => '24',
    'cat_name' => '耳坠',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '24',
    'name' => '耳坠',
  ),
);
?>